openapi: 3.0.0
info:
  title: Pizza Ordering API
  description: API for ordering pizzas and tracking orders
  version: 1.0.0

servers:
  - url: http://localhost:8000

paths:
  /menu:
    get:
      summary: Get pizza menu
      description: Retrieve the list of available pizzas
      responses:
        '200':
          description: A list of pizzas
          content:
            application/json:
              schema:
                type: object
                properties:
                  pizzas:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        sizes:
                          type: array
                          items:
                            type: string
                        price:
                          type: number

  /order:
    post:
      summary: Place a pizza order
      description: Create a new pizza order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pizza_name:
                  type: string
                size:
                  type: string
                quantity:
                  type: integer
      responses:
        '201':
          description: Order placed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: string
                  estimated_time:
                    type: integer

  /order/{order_id}:
    get:
      summary: Track an order
      description: Get order status using order ID
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order status
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: string
                  status:
                    type: string
                  estimated_time:
                    type: integer
